# Generated by Django 4.1.3 on 2022-12-26 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Educación', '0002_alumnos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('facultad', models.CharField(max_length=200)),
                ('tiempo', models.CharField(max_length=200)),
            ],
        ),
    ]
